services:
  - type: web
    name: stock-screener
    env: python
    buildCommand: "pip install -r requirements.txt && python data_generator.py"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0